// src/lib/components/CodeEditor.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import type * as Monaco from 'monaco-editor';
  import { NOCTURNE_THEME } from '$lib/client/monaco-theme';
  import { EDITOR_FONT, loadMonaco } from '$lib/client/monaco';

  interface Props {
    code: string;
    isEditable?: boolean;
    /** Highlights the line currently being written */
    streaming?: boolean;
    onChange?: (value: string) => void;
    onSave?: () => void;
  }

  let { code, isEditable = false, streaming = false, onChange, onSave }: Props = $props();

  let container = $state<HTMLDivElement>();
  let editor: Monaco.editor.IStandaloneCodeEditor | null = null;
  let monaco: typeof Monaco | null = null;
  let writingLine: Monaco.editor.IEditorDecorationsCollection | null = null;
  let isInitialMount = true;
  let isUserEditing = false;
  let userScrolledAway = false;
  let suppressChange = false;

  onMount(() => {
    let disposed = false;

    (async () => {
      const monacoMod = await loadMonaco();
      if (disposed || !container) return;
      monaco = monacoMod;

      editor = monaco.editor.create(container, {
        value: code,
        language: 'html',
        theme: NOCTURNE_THEME,
        readOnly: !isEditable,
        minimap: { enabled: true, renderCharacters: false, scale: 1, maxColumn: 80 },
        scrollBeyondLastLine: false,
        ...EDITOR_FONT,
        padding: { top: 12, bottom: 12 },
        renderLineHighlight: 'line',
        guides: { indentation: true },
        smoothScrolling: true,
        cursorBlinking: 'smooth',
        overviewRulerBorder: false,
        hideCursorInOverviewRuler: true,
        scrollbar: { verticalScrollbarSize: 8, horizontalScrollbarSize: 8, useShadows: false },
        wordWrap: 'on',
        automaticLayout: true
      });

      writingLine = editor.createDecorationsCollection();

      editor.addCommand(monaco.KeyMod.CtrlCmd | monaco.KeyCode.KeyS, () => onSave?.());

      // Scroll to the end on initial load
      const model = editor.getModel();
      if (isInitialMount && model) {
        editor.revealLine(model.getLineCount());
        isInitialMount = false;
      }

      editor.onDidChangeCursorPosition(() => {
        if (isEditable) isUserEditing = true;
      });

      editor.onDidScrollChange(() => {
        const model = editor?.getModel();
        if (!model) return;
        const visibleRanges = editor?.getVisibleRanges();
        if (!visibleRanges || visibleRanges.length === 0) return;
        const lastVisibleLine = visibleRanges[visibleRanges.length - 1].endLineNumber;
        userScrolledAway = lastVisibleLine < model.getLineCount() - 5;
      });

      editor.onDidChangeModelContent(() => {
        if (suppressChange) return;
        const value = editor?.getValue();
        if (onChange && value !== undefined) onChange(value);
      });

      syncEditorContent(code);
    })();

    return () => {
      disposed = true;
    };
  });

  onDestroy(() => {
    editor?.dispose();
  });

  function markWritingLine() {
    if (!editor || !writingLine || !monaco) return;
    const model = editor.getModel();
    if (!streaming || !model) {
      writingLine.clear();
      return;
    }
    const line = model.getLineCount();
    writingLine.set([
      {
        range: new monaco.Range(line, 1, line, 1),
        options: { isWholeLine: true, className: 'nocturne-writing-line' }
      }
    ]);
  }

  function syncEditorContent(next: string) {
    if (!editor) return;
    if (editor.getValue() === next) {
      markWritingLine();
      return;
    }

    suppressChange = true;
    editor.setValue(next);
    suppressChange = false;

    const model = editor.getModel();
    if (!isUserEditing && !isEditable && !userScrolledAway && model) {
      editor.revealLine(model.getLineCount());
    }
    markWritingLine();
  }

  // Sync external `code` changes into the editor without firing onChange
  $effect(() => {
    void streaming;
    syncEditorContent(code);
  });

  // Reflect readOnly + reset editing flag when edit mode changes
  $effect(() => {
    editor?.updateOptions({ readOnly: !isEditable });
    if (!isEditable) {
      isUserEditing = false;
      userScrolledAway = false;
    }
  });
</script>

<div class="h-full w-full overflow-hidden" bind:this={container}></div>

// components/code-editor.tsx
"use client"

import { useEffect, useRef, useState } from "react"
import dynamic from "next/dynamic"

const Editor = dynamic(() => import("@monaco-editor/react"), { ssr: false })

interface CodeEditorProps {
  code: string;
  isEditable?: boolean;
  onChange?: (value: string) => void;
}

export function CodeEditor({ code, isEditable = false, onChange }: CodeEditorProps) {
  const editorRef = useRef<any>(null);
  const [isInitialMount, setIsInitialMount] = useState(true);
  const [isUserEditing, setIsUserEditing] = useState(false);

  const handleEditorDidMount = (editor: any) => {
    editorRef.current = editor;

    // Only scroll to the end on initial load
    if (isInitialMount) {
      editor.revealLine(editor.getModel().getLineCount());
      setIsInitialMount(false);
    }

    // Add event listener for user interactions
    editor.onDidChangeCursorPosition(() => {
      if (isEditable) {
        setIsUserEditing(true);
      }
    });
  };

  const handleEditorChange = (value: string | undefined) => {
    if (onChange && value !== undefined) {
      onChange(value);
    }
  };

  useEffect(() => {
    if (editorRef.current) {
      // Only scroll to the end if the user is not actively editing
      // or if the editor is not in edit mode
      if (!isUserEditing && !isEditable) {
        editorRef.current.revealLine(editorRef.current.getModel().getLineCount());
      }
    }
  }, [code, isUserEditing, isEditable]);

  // Reset the isUserEditing status when edit mode is disabled
  useEffect(() => {
    if (!isEditable) {
      setIsUserEditing(false);
    }
  }, [isEditable]);

  return (
    <div className="h-full w-full overflow-hidden">
      <Editor
        height="100%"
        language="html"
        theme="vs-dark"
        value={code}
        options={{
          readOnly: !isEditable,
          minimap: { enabled: false },
          scrollBeyondLastLine: false,
          fontSize: 14,
          wordWrap: "on",
          automaticLayout: true, // Automatically adjusts the size
        }}
        onMount={handleEditorDidMount}
        onChange={handleEditorChange}
      />
    </div>
  )
}
